Add basic REPL
Update `is_end_of_file` to borrow lexer via `&self` instead of `self`.
This fixes an issue where trying to use `lexer.is_end_of_file()` within
a conditional was throwing this error:

```
error[E0507]: cannot move out of `*self` which is behind a mutable reference
   --> src/lexer.rs:136:12
    |
136 |         if self.is_end_of_file() {
    |            ^^^^ move occurs because `*self` has type `lexer::Lexer<'_>`, which does not implement the `Copy` trait
```